version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: koywe-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: koywe-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/koywe-challenge"
      JWT_SECRET: "miClaveSuperSecreta!2025"
    command: "npm run start:dev"

volumes:
  mongo-data:
